# Generated by Django 5.2.6 on 2025-09-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hero', '0006_hero_is_in_combat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('value', models.IntegerField(default=0)),
                ('hero_class_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.heroclass')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('defense', models.IntegerField(default=5)),
                ('armor_type', models.CharField(default='leather', max_length=50)),
                ('equipment_slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapon'), ('shield', 'Shield')], default='head', max_length=50)),
            ],
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('heal_amount', models.IntegerField(default=20)),
                ('mana_restore', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='OfHand',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('block', models.IntegerField(default=5)),
                ('shield_type', models.CharField(default='wooden', max_length=50)),
                ('equipment_slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapon'), ('shield', 'Shield')], default='shield', max_length=50)),
            ],
            bases=('item.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('damage', models.IntegerField(default=10)),
                ('weapon_type', models.CharField(default='sword', max_length=50)),
                ('equipment_slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapon'), ('shield', 'Shield')], default='weapon', max_length=50)),
            ],
            bases=('item.item',),
        ),
    ]
