# Generated by Django 5.2.6 on 2025-09-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('off_hand', 'Off_hand'), ('armor', 'Armor'), ('consumable', 'Consumable')], default='armor', max_length=50),
        ),
        migrations.AddField(
            model_name='consumable',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('off_hand', 'Off_hand'), ('armor', 'Armor'), ('consumable', 'Consumable')], default='consumable', max_length=50),
        ),
        migrations.AddField(
            model_name='ofhand',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('off_hand', 'Off_hand'), ('armor', 'Armor'), ('consumable', 'Consumable')], default='off_hand', max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='item_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('off_hand', 'Off_hand'), ('armor', 'Armor'), ('consumable', 'Consumable')], default='weapon', max_length=50),
        ),
    ]
