# Generated by Django 5.2.6 on 2025-09-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_armor_item_type_consumable_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffHand',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('block', models.IntegerField(default=5)),
                ('shield_type', models.CharField(default='wooden', max_length=50)),
                ('equipment_slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapon'), ('shield', 'Shield')], default='shield', max_length=50)),
            ],
            bases=('item.item',),
        ),
        migrations.RemoveField(
            model_name='armor',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='item_type',
        ),
        migrations.DeleteModel(
            name='OfHand',
        ),
    ]
