# Generated by Django 5.2.6 on 2025-09-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('item', '0003_offhand_remove_armor_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='consumable',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='offhand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
