# Generated by Django 5.2.6 on 2025-09-10 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_rename_health_hero_max_health_and_more'),
        ('item', '0004_alter_armor_options_alter_consumable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='hero.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hero.hero')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('legs', 'Legs'), ('feet', 'Feet'), ('hands', 'Hands'), ('weapon', 'Weapon'), ('shield', 'Shield')], max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='item.equipment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            options={
                'unique_together': {('equipment', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'unique_together': {('inventory', 'item')},
            },
        ),
    ]
