# Generated by Django 5.2.6 on 2025-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_armor_equipment_slot_alter_equipmentslot_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='equipment_slot',
            field=models.CharField(choices=[('head', 'Head'), ('armor', 'Armor'), ('main_hand', 'Main_hand'), ('offhand', 'Offhand'), ('consumable_1', 'Consumable_1'), ('consumable_2', 'Consumable_2'), ('consumable_3', 'Consumable_3'), ('legs', 'Legs'), ('hands', 'Hands')], default='head', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot',
            field=models.CharField(choices=[('head', 'Head'), ('armor', 'Armor'), ('main_hand', 'Main_hand'), ('offhand', 'Offhand'), ('consumable_1', 'Consumable_1'), ('consumable_2', 'Consumable_2'), ('consumable_3', 'Consumable_3'), ('legs', 'Legs'), ('hands', 'Hands')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offhand',
            name='equipment_slot',
            field=models.CharField(choices=[('head', 'Head'), ('armor', 'Armor'), ('main_hand', 'Main_hand'), ('offhand', 'Offhand'), ('consumable_1', 'Consumable_1'), ('consumable_2', 'Consumable_2'), ('consumable_3', 'Consumable_3'), ('legs', 'Legs'), ('hands', 'Hands')], default='offhand', max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equipment_slot',
            field=models.CharField(choices=[('head', 'Head'), ('armor', 'Armor'), ('main_hand', 'Main_hand'), ('offhand', 'Offhand'), ('consumable_1', 'Consumable_1'), ('consumable_2', 'Consumable_2'), ('consumable_3', 'Consumable_3'), ('legs', 'Legs'), ('hands', 'Hands')], default='main_hand', max_length=50),
        ),
    ]
