# Generated by Django 5.2.6 on 2025-09-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_armor_equipment_slot_alter_equipmentslot_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='hero',
        ),
    ]
