# Generated by Django 5.2.6 on 2026-02-06 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_inventory_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.item')),
                ('critical_bonus', models.IntegerField(default=0)),
                ('status_immunities', models.JSONField(blank=True, default=list)),
                ('passive_effects', models.JSONField(blank=True, default=dict)),
                ('accessory_type', models.CharField(default='ring', max_length=50)),
                ('equipment_slot', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], default='accessory', max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('item.item',),
        ),
        migrations.RemoveField(
            model_name='armor',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='damage',
        ),
        migrations.AddField(
            model_name='armor',
            name='defense_bonus',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='armor',
            name='elemental_resistances',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='armor',
            name='health_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='accuracy_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='element',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('ice', 'Ice'), ('lightning', 'Lightning'), ('earth', 'Earth'), ('wind', 'Wind'), ('holy', 'Holy'), ('dark', 'Dark')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='equipment_slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], default='armor', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentslot',
            name='slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offhand',
            name='equipment_slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], default='accessory', max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equipment_slot',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], default='weapon', max_length=50),
        ),
    ]
