# Generated by Django 5.2.6 on 2026-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_accessory_remove_armor_defense_remove_weapon_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level_requirement',
            field=models.IntegerField(default=1),
        ),
    ]
