# Generated by Django 5.2.6 on 2026-02-08 20:15

from django.db import migrations


def delete_offhand_items(apps, schema_editor):
    """Delete all OffHand items from the database"""
    # Get the Item model (base class) to delete polymorphic OffHand items
    Item = apps.get_model('item', 'Item')
    # Delete items where polymorphic_ctype points to OffHand
    ContentType = apps.get_model('contenttypes', 'ContentType')
    try:
        offhand_ctype = ContentType.objects.get(app_label='item', model='offhand')
        Item.objects.filter(polymorphic_ctype=offhand_ctype).delete()
    except ContentType.DoesNotExist:
        # If ContentType doesn't exist, nothing to delete
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_level_requirement'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(delete_offhand_items, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='OffHand',
        ),
    ]
