# Generated by Django 5.2.6 on 2026-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_offhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessory',
            name='magic_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessory',
            name='magic_defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessory',
            name='speed_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='magic_defense_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
