# Generated by Django 5.2.6 on 2025-09-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('base_health', models.IntegerField(default=100)),
                ('base_strength', models.IntegerField(default=10)),
                ('base_agility', models.IntegerField(default=10)),
                ('base_intelligence', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('hero_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.heroclass')),
            ],
        ),
    ]
