# Generated by Django 5.2.6 on 2025-09-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_constitution_alter_hero_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heroclass',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
