# Generated by Django 5.2.6 on 2025-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_hero_id_alter_heroclass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroclass',
            name='base_constitution',
            field=models.IntegerField(default=10),
        ),
    ]
