# Generated by Django 5.2.6 on 2025-09-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_heroclass_base_constitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='current_health',
            field=models.IntegerField(default=100),
        ),
    ]
