# Generated by Django 5.2.6 on 2025-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_hero_current_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='is_in_combat',
            field=models.BooleanField(default=False),
        ),
    ]
