# Generated by Django 5.2.6 on 2025-09-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_hero_is_in_combat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='current_mana',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hero',
            name='mana',
            field=models.IntegerField(default=50),
        ),
    ]
