# Generated by Django 5.2.6 on 2025-09-10 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_hero_current_mana_hero_mana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='health',
            new_name='max_health',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='mana',
            new_name='max_mana',
        ),
    ]
