# Generated by Django 5.2.6 on 2025-09-15 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_hero_inventory'),
        ('item', '0008_remove_inventory_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.inventory'),
        ),
    ]
